# developer docker compose file, extends docker-compose.yml
version: '3.9'
services:
  flask:
    ports:
      - 80:5000
    volumes:
      - './:/app'
    env_file: 
      - ./.env.dev
  db:
    environment:
      POSTGRES_PASSWORD: DevPassword
      POSTGRES_USER: DevUser
      POSTGRES_DB: DevDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
  celery_worker:
    volumes:
      - './:/app'
    env_file: 
      - ./.env.dev
  celery_beat:
    volumes:
      - './:/app'
    env_file: 
      - ./.env.dev
  celery_flower:
    ports:
      - 5555:5555
    volumes:
      - './:/app'
    env_file: 
      - ./.env.dev

volumes:
  postgres_data: